import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar/Navbar';
import BottomNavbar from './components/Navbar/BottomNavbar';
import Footer from './components/Footer';
import Providers from './components/Providers';
import CartGetter from './components/CartGetter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sisley Bolivia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <CartGetter>
            <Navbar />
            {children}
            <Footer />
            <BottomNavbar />
          </CartGetter>
        </Providers>
      </body>
    </html>
  );
}
